### ISSUE TITLE
CMS 5.1 compatibility

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/recipe-solr-search#20]
Is there an ETA when this will become updated to work with CMS 5.1 recipe? Thanks.

Also should the default branch be changed to 3?

**Comment by GuySartorelli** [comment]
Official support for this recipe was dropped with 5.0.0 as [noted in the changelog](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#modules-not-supported-going-forward), so the CMS Squad won't be making any changes to it from here on.

**Comment by michalkleiner** [comment]
Thanks. Best bet for anyone who comes across this (as mentioned in another similar issue) is to [inline the recipe](https://github.com/silverstripe/recipe-plugin?tab=readme-ov-file#inlining-recipes) into their own project.
