### ISSUE TITLE
Config doesn't work out of the box for SCP(S)

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/recipe-solr-search#5]
On CCL, the Solr server is a shared service - this means that it has it's own cron job that runs to "commit" index updates and keep search results current. However, on SCP(S) each environment has it's own Solr server, and thus needs to ensure that updates are forcibly changed.

There are two ways to achieve this:

1) [update the Solr config AutoSoftCommit value](https://github.com/silverstripe/silverstripe-fulltextsearch/pull/278/files?w=1#diff-e4801c219ed91ca81d63a9e3dfc0f18ede66493e128f1ef7f83a2fb325b74bfaR382) as per @chillu's PR against the FTS module itself
2) [update the Solr config AutoCommit OpenSearcher](https://github.com/silverstripe/silverstripe-fulltextsearch/blob/3/conf/solr/4/extras/solrconfig.xml#L372) value from `false` to `true`

Each of these changes can be made on a project level by manually adding an update `solrconfig.xml` to the configuration via:

```php
Solr::configure_server([
	'extraspath' => Director::baseFolder() . '/path/to/solrconfig/',
```

But it would make sense ([if we are looking at a split of recipes](https://github.com/silverstripe/recipe-solr-search/issues/4) to make these changes at the recipe-level

**Comment by GuySartorelli** [comment]
The PR linked above has been merged. I think this solves the problem - if not, feel free to reopen.
